### PR TITLE
improved performance for px:fileset-load and px:fileset-add-entry, migrated old tests to xspec/xprocspec, also made some fixes in file-/fileset-utils

### PR DESCRIPTION
**Pull request by josteinaj**
fixes daisy/pipeline-issues#449
fixes daisy/pipeline-issues#324

## performance

 * added sample for testing fileset-load performance
   * basic measurement using this sample indicates that this commit cuts the time spent in `px:fileset-load` in half (i.e. double the performance)
 * px:fileset-load
   * dont normalize all in-memory documents each time a `d:file` is evaluated
   * create in-memory fileset and normalize documents in the same `p:for-each`
   * make `px:fileset-add-entry` responsible for URI normalization (XSLT no longer invoked from fileset-load)
 * px:fileset-add-entry
   * externalized d:file normalizer XSLT
   * only invoke fileset normalization if the URI contains certain characters or strings
     * this check is just a very rudamentary (and hopefully efficient since there's almost no regexes except a `tokenize(.,'%')`) check that lets us skip most normalizations. Tested with both typical Windows and Linux `file:`-URIs.

## tests

 * uri-functions.xsl
   * support "mailto:"
   * fix "dir/.." normalization
   * fix px:longest-common-uri so it compares all uris, not just the first two
   * migrated some xspec tests to file-utils that used to be utf-x tests in fileset-utils
 * fileset-utils
   * enable xprocspec testing
   * migrated old xproc tests to xprocspec
   * migrated old utf-x tests to xspec
   * moved fileset.rnc under src/main/resources, updated it to support `d:ref` and added it to the xml catalog
   * support relative hrefs in `px:fileset-filter`
   * make fileset-join.xsl testable with xspec by not using global variables and making it possible to pass a custom set of documents in instead of always using the `collection()`
   * added mock steps for common-utils, file-utils, html-utils and zip-utils; also enabled the file-utils Java implementations from calabash

### CODE REVIEW

**Comment by josteinaj** [comment]
@bertfrees do you want to include your changes to the fileset-utils tests here before merging to master?

**Comment by josteinaj** [comment]
Hmm, one of the tests failed on travis. I'll have a look at it if @bertfrees does not merge with his branch.

**Comment by josteinaj** [comment]
Triggered a Travis re-run and this time it passed. Weird.

**Comment by bertfrees** [comment]
Great work Jostein! The changes I had were almost identical to yours but you had converted much more tests.

I had the problem of steps being loaded twice from different URIs and therefore causing some error. It looks like you had the same problem and you fixed it by replacing `p:import href="http://www.daisy.org/pipeline/modules/fileset-utils/library.xpl"/>` with `<p:import href="fileset-library.xpl"/>` at some places.

Tests I had that you didn't have yet:
- fileset-store.xprocspec
- some tests for ZIP href's

Some other differences are:
- I had left the sample files in src/test/resources.
- I used Pax-Exam instead of mocks of the dependencies

**Comment by bertfrees** [comment]
See commit https://github.com/daisy/pipeline-modules-common/commit/92be441fc134b9ca917f1a9644dc8f17a264ee6e for how  to use Pax-Exam to run the XProcSpec tests

**Comment by josteinaj** [comment]
Looks good. So I guess we're ready to merge @rdeltour ?

**Comment by rdeltour** [comment]
Looks great at first sight. I'd like to do a more detailed review however before merging, mostly to make sure I'm aware of all the details.
@josteinaj do you depend on this for the nordic scripts? Are you on a deadline?

**Comment by josteinaj** [comment]
@rdeltour I'm already using this. I make copies of things I need in the nordic scripts and remove them again when the official modules are released. And I expect to keep doing it that way until we get a update client and automatic deployments of changes to the master branches.

**Comment by josteinaj** [comment]
replaced by daisy/pipeline-modules-common#90

**Pull request closed without merging**
