### PR TITLE
px:fileset-store: support !/ in target HREFs of file sets

### PR DESCRIPTION
**Pull request by bertfrees**
see issue #70

### CODE REVIEW

**Comment by bertfrees** [comment]
Rebased on v1.9

**Comment by josteinaj** [comment]
This introduces a circular dependency with zip-utils.

@bertfrees Should be join zip-utils into fileset-utils or should we keep them decoupled by somehow moving the stuff you have here out of fileset-utils?

**Comment by bertfrees** [comment]
Didn't realize there was a circular dependency. I've used it and I didn't run into trouble. So does it matter you think? Is the circular dependency on the bundle level or on a step level?

**Comment by josteinaj** [comment]
On the bundle level I think.

**Comment by josteinaj** [comment]
I'll move px:unzip-fileset from zip-utils to fileset-utils to avoid the circular dependency.

**Comment by josteinaj** [comment]
replaced by daisy/pipeline-modules-common#90

**Pull request closed without merging**
